### PR TITLE
.gitmodules: Make submodules shallow, fix url

### PR DESCRIPTION
**Pull request by Margen67**

### CODE REVIEW

**Comment by thrimbor** [comment]
I don't think we should make submodules shallow by default.

**Comment by Margen67** [comment]
> 
> 
> I don't think we should make submodules shallow by default.

Why?

**Comment by thrimbor** [comment]
Because it requires the user to undertake additional steps before they can use tools that I think are essential, such as bisection. From my perspective, shallow cloning serves one of two purposes, either saving bandwidth or disk space. Imho these are better addressed in different ways, like shallow cloning in CI, manual shallow cloning by the user if disk space or bandwidth is tight, reducing the overall amount of submodules we carry in the main nxdk repo etc.

**Comment by JayFoxRox** [comment]
I agree with @thrimbor.

Users are already told to shallow-clone here: https://github.com/XboxDev/nxdk/wiki/Install-the-Toolchain.
The README is just outdated *again*. therefore I decided to reopen https://github.com/XboxDev/nxdk/issues/73#issuecomment-612397420 (due to a lack of counter-arguments).

**Pull request closed without merging**
