### PR TITLE
pbkit: Support non-standard NVCLK

### LINKED ISSUE #536: pbkit quits if the nvclk freq is not default
It shouldn't do this.

https://github.com/XboxDev/nxdk/blob/master/lib/pbkit/pbkit.c#L2815

### PR DESCRIPTION
**Pull request by GXTX**
Fixes #536 

With the release of [software based overclocks](https://github.com/GXTX/XboxOverclock), and hardware modding becoming more popular I think pbkit should support any given frequency just as XDK does. A stock Xbox will run fine at ~250MHz and as low as ~25MHz.

### CODE REVIEW

**Comment by Ryzee119** [comment]
Looks pretty good, tested on my 1.6 with stock clocks and didnt break anything.
Got this output:
```
input freq : 233338Hz
num        : 58334
den        : 7812
timer freq : 31248Hz
```
Output matches the original hardcoded value of ~31.25Mhz

**Comment by GXTX** [comment]
Thanks for the review. ^

**Comment by Ernegien** [comment]
Closing due to lack of MIT consent.

**Comment by GXTX** [comment]
The code is taken directly from Linux, I cannot re-license Linux.

**Comment by JayFoxRox** [comment]
Could be rewritten to simplify fractions using a GCD, or you can find a source for fraction simplification using this algorithm to ensure it's factual / non-copyrightable (while also providing a second source).

I think it *is* already factual, although I don't fully understand the choice of the constant 32 and 5.

**Pull request closed without merging**
