### PR TITLE
ci: Add log separators for each sample

### PR DESCRIPTION
**Pull request by ReenigneArcher**
This PR adds expandable divisions for each section when building samples in CI.

image

### CODE REVIEW

**Comment by thrimbor** [comment]
Hm, could be a little confusing due to how building nxdk is mixed into building the first sample (not your fault), but I still like it.
Commit title doesn't quite follow nxdk's convention though, could you please change it to `ci: Add log separators for each sample`? (`ci` prefix and capitalized first letter after the colon)

**Comment by ReenigneArcher** [comment]
Updated.

**Comment by ReenigneArcher** [comment]
> could be a little confusing due to how building nxdk is mixed into building the first sample (not your fault)

Pushed a change to address this.

**Comment by thrimbor** [comment]
Did you intend to combine the changes into one commit? It's a bit weird now with the title not describing the more important change

**Comment by ReenigneArcher** [comment]
Yes and not sure what you mean, really. IMO, the important change in this PR is dividing the sample build logs.

**Comment by thrimbor** [comment]
That's what I mean, dividing the build logs is the significant change, but the commit title is  `ci: Build nxdk before samples`, not even mentioning it.

**Comment by ReenigneArcher** [comment]
Oh... that's what I get for doing this in the middle of the night. Updated it.

Also FYI, you can do "squash and merge" and make the commit messages whatever you want in your repo upon merge.

**Pull request merged**
